package com.epfl.ch.seizureguard.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFFE57373)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFEBEE)
val onPrimaryContainerLight = Color(0xFF442C2E)
val secondaryLight = Color(0xFFFF8A65)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFBE9E7)
val onSecondaryContainerLight = Color(0xFF442C2E)
val tertiaryLight = Color(0xFFFFB74D)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFF3E0)
val onTertiaryContainerLight = Color(0xFF442C2E)
val errorLight = Color(0xFFEF5350)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFEBEE)
val onErrorContainerLight = Color(0xFF442C2E)
val backgroundLight = Color(0xFFFAF7F7)
val onBackgroundLight = Color(0xFF442C2E)
val surfaceLight = Color(0xFFFFFAFA)
val onSurfaceLight = Color(0xFF442C2E)
val surfaceVariantLight = Color(0xFFEEDEE7)
val onSurfaceVariantLight = Color(0xFF4E444B)
val outlineLight = Color(0xFF7F747C)
val outlineVariantLight = Color(0xFFD1C3CB)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF352E33)
val inverseOnSurfaceLight = Color(0xFFFAEDF4)
val inversePrimaryLight = Color(0xFFF0B3E7)
val surfaceDimLight = Color(0xFFE3D7DD)
val surfaceBrightLight = Color(0xFFFFF7F9)
val surfaceContainerLowestLight = Color(0xFFFFFAFA)
val surfaceContainerLowLight = Color(0xFFF8F3F3)
val surfaceContainerLight = Color(0xFFF5F0F0)
val surfaceContainerHighLight = Color(0xFFF2EDED)
val surfaceContainerHighestLight = Color(0xFFEFEAEA)

// ================================ Dark Theme Colors ================================
val primaryDark = Color(0xFFFFB74D)
val onPrimaryDark = Color(0xFF442C2E)
val primaryContainerDark = Color(0xFF2D2522)
val onPrimaryContainerDark = Color(0xFFFFDBAF)
val secondaryDark = Color(0xFFFF8A65)
val onSecondaryDark = Color(0xFF442C2E)
val secondaryContainerDark = Color(0xFF2D2522)
val onSecondaryContainerDark = Color(0xFFFFCCBC)
val tertiaryDark = Color(0xFFE57373)
val onTertiaryDark = Color(0xFF442C2E)
val tertiaryContainerDark = Color(0xFF2D2522)
val onTertiaryContainerDark = Color(0xFFFFEBEE)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1A1717)
val onBackgroundDark = Color(0xFFEEE0E0)
val surfaceDark = Color(0xFF2D2522)
val onSurfaceDark = Color(0xFFEEE0E0)
val surfaceVariantDark = Color(0xFF4E444B)
val onSurfaceVariantDark = Color(0xFFD1C3CB)
val outlineDark = Color(0xFF9A8D95)
val outlineVariantDark = Color(0xFF4E444B)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEBDFE6)
val inverseOnSurfaceDark = Color(0xFF352E33)
val inversePrimaryDark = Color(0xFF7F4D7A)
val surfaceDimDark = Color(0xFF171216)
val surfaceBrightDark = Color(0xFF3E373C)
val surfaceContainerLowestDark = Color(0xFF241E1B)
val surfaceContainerLowDark = Color(0xFF2D2522)
val surfaceContainerDark = Color(0xFF332A26)
val surfaceContainerHighDark = Color(0xFF3A302B)
val surfaceContainerHighestDark = Color(0xFF423631)


